### ISSUE TITLE
Difficulties to install on debian buster

### ISSUE THREAD

**Issue by arthurlutz** [dariusk/express-activitypub#11]
I am getting some errors while trying to install on buster node12 : 

```
npm ERR! Failed at the generate-rsa-keypair@0.1.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

which leads me to https://github.com/LinusU/node-generate-rsa-keypair/issues/5 & the associated merge request : https://github.com/LinusU/node-generate-rsa-keypair/pull/6

Fixed it with : 

```
npm install LinusU/node-generate-rsa-keypair
```

(which gets version 0.2.1)

**Comment by vitalyster** [comment]
This package is not a dependency anymore, please use latest master branch of express-activitypub

**Comment by arthurlutz** [comment]
@vitalyster hey! thanks for taking the time to look at this and respond! 

I am on the `master` branch, so I'm not sure what I need to change...

**Comment by arthurlutz** [comment]
oh, sorry, I got mixed up, this issue should be filed on https://github.com/dariusk/rss-to-activitypub, let me move it. (sorry for the noise)
