### ISSUE TITLE
Doesn't work with Mastodon correctly anymore

### ISSUE THREAD

**Issue by protheory8** [dariusk/express-activitypub#12]
@dariusk Mastodon now requires digest header in signature, so accepting follow requests and sending messages doesn't work anymore.

**Comment by protheory8** [comment]
Turns out Pleroma responds with error too

**Comment by protheory8** [comment]
I tried to add `digest` header using `const digestHash = crypto.createHash('sha256').update(JSON.stringify(message)).digest('base64');` and then changing `header` and `stringToSign` variables in `signAndSend` function in `routes/inbox.js` file, but now Mastodon responds with 500.

**Comment by protheory8** [comment]
So I've just tried another way to generate `digest` header, but unfortunately it didn't work either.

**Comment by protheory8** [comment]
@vitalyster Sorry for an unexpected mention, but do you know how to fix this by any chance?

**Comment by protheory8** [comment]
I asked for help at https://socialhub.activitypub.rocks and they figured out how to fix this issue.

**Comment by flberger** [comment]
I can confirm that it still does not work with Mastodon: follow requests are not being accepted. If pull request #13 fixes this, it would be nice to have it accepted.

**Comment by dariusk** [comment]
Sorry about that. Merged.
