### ISSUE TITLE
Is it a simple / light activitypub server / backend?

### ISSUE THREAD

**Issue by pwFoo** [dariusk/express-activitypub#3]
I searching for a light activitypub backend to handle federation and local users like mastodon or other examples do.

Is there some more documentation about features, usage or a demo?

**Comment by dariusk** [comment]
Sorry it took me forever to get back to this. I believe I've documented what it is able to do, and I'm trying to keep the code simple enough that you can reference the code. You should be able to get it running locally pretty quickly using the instructions in the readme.
