### ISSUE TITLE
Alternate database backend?

### ISSUE THREAD

**Issue by pwFoo** [dariusk/express-activitypub#4]
Is it possible to implement / switch database backends like mysql?

**Comment by dariusk** [comment]
I have no plans to implement an alternate database backend but the queries are simple enough that it should not be a ton of work to port it to a different DB. I'm trying to keep this code base as light as possible so I won't be supporting many features or databases or anything like that. It's really meant as a starting point so other people can build on top of it or heavily modify it. Think of it like "Hello, world" for NodeJS ActivityPub.
