### ISSUE TITLE
Doesn't work correctly over http

### ISSUE THREAD

**Issue by PaulKiddle** [dariusk/express-activitypub#7]
I'm just trying to use this as a quick and easy local test server, without bothering about ssl.
Unfortunately while you can start the server without ssl config, there are a number of places where "https" is hardcoded in urls, making it difficult to use without adding dirty hacks to my own project.

**Comment by dannyhpy** [comment]
Replace any occurence of "https" by `req.protocol`
It should be enough.

**Comment by getgle** [comment]
Use HTTPS
